### ISSUE TITLE
Change in Lexer Rules is not applied when debuging

### ISSUE THREAD

**Issue by sirgru** [mike-lischke/vscode-antlr4#45] opened 2018-08-30 12:19 UTC
When using 2 separate files for Parser and Lexer, after the Lexer rule is changed, the IDE picks up on the change but the debugger doesn't. It displays the diagram with the old Lexer rules. Deleting the generated .antlr folder makes no difference, the only thing that helps is re-starting VS Code.

```
VS Code 1.26.1

> java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

antlr-4.7.1-complete

Windows 8.1
```

**Comment by sirgru** [comment] 2018-09-01 14:49
I noticed this happens also in Netbeans and *sometimes* even in IntelliJ Idea plugin, but it seems it only happens when a lexer alternative is added. This leads me to believe it may have to do something with Antlr itself.

Also, it happens on 2 PCs, the other on Windows 7.

**Comment by mike-lischke** [comment] 2018-09-10 07:06
I cannot reproduce this problem. All the files used by the debugger are stored in the .antlr folder. If you delete that and regenerate the interpreter data (by saving your grammar) the updated files are written and should be picked up by the debugger too.

The debug adapter, which loads this data, is recreated every time when a new debug session starts, so there can't be any caching effect be involved here. Pretty odd problem...

**Comment by Alex206** [comment] 2018-09-10 23:01
Hi, I'm having the same problem. I work only with Visual Studio Code and it does not always happen. I will try deleting the files in the .antlr folder and give you feedback then.

**Comment by sirgru** [comment] 2018-10-02 16:46
I'll investigate a little more later and add a gif or something.

**Comment by borzag** [comment] 2020-04-15 10:11
I have the same problem. It seems that it's enough to close the parser file (and maybe lexer file) and  reopen it for the parser to read the changes in the lexer file.

I'm running ANTLR4 grammar syntax support:
v.2.2.3 

and VS Code:
Visual Studio Code
Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z (4 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by AlanChurchill** [comment] 2020-05-28 05:05
I have the same issue. I do 1 of 3 things to fix it: 1) rerun the parser (rarely works), 2) close parser file and re-open (mostly works), 3) restart VSCode (always works)

**Comment by mike-lischke** [comment] 2020-07-19 09:18
I'm afraid I can't do anything about this problem if I don't get a step list how to recreate the issue, as for it works everytime. Maybe I don't test a specific combination of things and therefor don't see the issue. Hence, without a reproducible case I will close this issue in a couple of days.

**Comment by AlanChurchill** [comment] 2020-07-22 06:42
Mike, that is fine. The work you have done for this tool is tremendous.

It may be environment specific so I can't produce a case that illustrates it. Since it has been reported by more than 1 person, something causes it. We are all developers so we know how hard it is to debug the unreproducible bug. Unless time opens up to dig deeper, it will have to remain.

Thanks again for everything.

**Closed** 2020-07-26 10:22 UTC
