### ISSUE TITLE
Graphs not rendering

### ISSUE THREAD

**Issue by brikken** [mike-lischke/vscode-antlr4#47] opened 2018-09-19 18:39 UTC
None of the graphs are rendering (parse tree, rule, call graph). Just a grey box is shown.

![image](https://user-images.githubusercontent.com/17687681/45773830-a9ac2380-bc4b-11e8-8c0f-b8c5efb17193.png)

Grammar (datadef.g4)
```
grammar datadef;

file: tabledef*;
tabledef: ID '{' ('types' '{' typedef (',' typedef)* '}')? memdef (',' memdef)* '}' ';';
typedef: ID ':' typeref;
memdef: ID ':' typeref;
typeref: (ID | PRIMITIVE)+;

PRIMITIVE: 'str' | 'num';
ID: [a-zA-Z_][a-zA-Z0-9_-]*;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
LINE_COMMENT: '//' ~[\r\n]* -> skip;
WHITESPACE: [ \t\f\r\n] -> channel(HIDDEN);
INVALID_INPUT: [\u0001-\u0008] | '\u000B' | '\u000C' | [\u000E-\u001F];
```

Test input (input.def)
```
MyTable {
    types {
        type1 : num str num,   // comment 1
        type2 : num type1 str
    }
    mem1: num str type1,
    mem2: num,
    mem3: type1 type1 type2
};

// comment 2
```

Debug configuration
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "antlr4-datadef",
            "type": "antlr-debug",
            "request": "launch",
            "input": "input.def",
            "grammar": "datadef.g4",
            "startRule": "file",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}
```

**Comment by mike-lischke** [comment] 2018-10-14 12:58
I cannot reproduce this problem. Does the textual parse tree appear (in the console window)? Have you tried to force a generation by changing something in the grammar and save it? Do you see an error message about the ANTLR extension in the dev tools (Menu -> Help -> Show Developer Tools)?

**Comment by mike-lischke** [comment] 2018-10-20 12:44
I guess this is the same like #44 and #52. Your `file` rule can match the empty string, which is a bad condition anyway.

**Comment by ebugusey** [comment] 2018-10-31 12:15
I have the same issue. But my grammar doesn't generate empty strings.

I have used grammar from "getting started" example of antlr4.
```antlr
grammar Hello;
start: r EOF;
r: 'hello' ID; // match keyword hello followed by an identifier
ID: [a-z]+; // match lower-case identifiers
WS: [ \t\r\n]+ -> skip; // skip spaces, tabs, newlines
```
launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "antlr-debug",
            "request": "launch",
            "name": "antlr4-test",
            "grammar": "Hello.g4",
            "startRule": "start",
            "input": "input.txt",
            "printParseTree": true,
            "visualParseTree": true,
        }
    ]
}
```
input.txt
```
hello test
```
Debug console says
```
Parse Tree:
start (
 r (
  "hello"
  "id"
 )
)
```
As expected.

There is no errors in Output windows.

There are errors in Developers Tools console:
```
webviewElement.ts:124 [Embedded Page] Uncaught ReferenceError: d3 is not defined
webviewElement.ts:124 [Embedded Page] Uncaught TypeError: Cannot read property 'nodeSize' of undefined
```

**Comment by mike-lischke** [comment] 2018-10-31 20:20
@ebugusey Obviously your node modules are not complete. The D3.js lib is missing. I wonder how you managed not to install that, since this is done automatically on installation of the vscode extension.

**Comment by ebugusey** [comment] 2018-11-01 08:55
Are you using D3 for parse tree visualization only? Because railroad diagrams and ATN graphs visualization works just fine.

**Comment by mike-lischke** [comment] 2018-11-01 08:59
Railroad diagrams use a separate script, but the ATN graphs do use D3. But why would it work in one graph and not the other? All the D3.js graphs a generated in the same way.

**Comment by mike-lischke** [comment] 2018-12-20 13:54
@ebugusey I just remembered that the D3.js lib is downloaded before first use and if you are in a restricted network (VPN or similar) this won't happen and hence D3 is not available in vscode. I have seen all kind of odd behavior when you launch vscode after an update and you cannot freely access the internet.

**Comment by mike-lischke** [comment] 2018-12-22 10:43
Should be fixed with the next release of the extension. If not, please reopen this issue.

**Closed by mike-lischke** 2018-12-22 10:43 UTC
Labels: bug
