### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Naghme98** [mike-lischke/vscode-antlr4#77] opened 2019-04-05 15:57 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.1.1`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/nic/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mike-lischke** [comment] 2019-04-05 17:53
Duplicate of issue #75

**Closed by mike-lischke** 2019-04-05 17:53 UTC
Labels: duplicate
