### ISSUE TITLE
Parse tree rendering fails in the presence of rules matching an empty string

### ISSUE THREAD

**Issue by MDoerner** [mike-lischke/vscode-antlr4#52] opened 2018-10-20 11:39 UTC
I have the issue mentioned in the title in the current version in the VS Marketplace (2.0.4).

MCVE:

grammar:
```
grammar TreeVisualizationFail;

LETTER : [a-zA-Z];
DIGIT : [0-9];

 
startRule : digits letters EOF;

letters : LETTER+;

digits : DIGIT*;
```

input:
```
foo
```

Note that for the given input the mandatory rule `digits` in `startRule` matches no tokens, i.e. an empty string.

After making `digits` optional in `startRule` and forcing `digits` to match at least one digit, the parse tree visualization gets generated.

Originally, I encountered this problem with a grammar used to parse VBA.

**Comment by mike-lischke** [comment] 2018-10-20 12:42
That's kinda duplicate of #44. The cause is the same. The underlying antlr4ts library tries to optimize the ATN from this grammar and fails.

However, matching an empty input string is a problem anyway and must be avoided. ANTLR4 will issue a warning for that.

**Comment by MDoerner** [comment] 2018-10-20 17:52
Just as a small note: Antlr only generates a warning for a rule matching an empty string if this rule is made optional in another rule using it. (In that case, the outcome is non-deterministic.)

**Comment by mike-lischke** [comment] 2018-10-20 18:11
I see. Didn't thought of that use (why would one want a node for nothing match?), but it seems people have their own use cases. Thanks.

**Comment by mike-lischke** [comment] 2018-10-20 18:14
@Vogel612 The reason for the parse tree not showing up is an exception in the antrl4ts runtime, when it tries to optimize the generated ATN. This shortcuts the visual parse tree generation. The only thing I can do about this is to disable the optimization, but I don't know what side effects that might have (as disabling this code path is not intended).

**Closed** 2018-12-17 15:30 UTC
Labels: bug
