### ISSUE TITLE
Cannot read test input file ${workspaceFolder}\${command:AskForTestInput}

### ISSUE THREAD

**Issue by RobertBaruch** [mike-lischke/vscode-antlr4#56] opened 2018-10-28 17:45 UTC
Windows 10, vscode 1.28.2.

launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "antlr-debug",
            "request": "launch",
            "name": "Run ANTLR4 Parser",
            // "input": "Input.txt",
            "input": "${workspaceFolder}/${command:AskForTestInput}",
            "grammar": "Hello.g4",
            "startRule": "r",
            "printParseTree": true,
            "visualParseTree": true
        }
    ]
}
```

This results in the error `Cannot read test input file: f:\antlrtest\${workspaceFolder}\${command:AskForTestInput}`

**Comment by mike-lischke** [comment] 2018-10-28 19:08
Duplicate of #48.

**Closed by mike-lischke** 2018-10-28 19:08 UTC
