### ISSUE TITLE
Extension does not work on Windows

### ISSUE THREAD

**Issue by kaby76** [mike-lischke/vscode-antlr4#235] opened 2023-11-08 16:15 UTC
There are numerous issues with the extension, and I am debugging it on Windows to find out why nothing works for me.

* In [src/backend/facade.ts, loadGrammar()](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/src/backend/facade.ts#L87) is called and "source" is null. The code this tries to read the file and assign "source". The first problem is that there are two types of paths: relative and absolute. [This code does a "join"](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/src/backend/facade.ts#L92C33-L92C67) of two absolute paths on Windows, e.g., `"C:\Users\kenne\AppData\Local\Programs\Microsoft VS Code\` and `c:\msys64\home\Kenne\foobar\Test.g4`. The result is a nonsensical path: `"C:\Users\kenne\AppData\Local\Programs\Microsoft VS Code\c:\msys64\home\Kenne\foobar\Test.g4"`. This code needs to use [path.isAbsolute()](https://www.w3schools.com/nodejs/met_path_isabsolute.asp) and perform the correct thing. If `filename` is absolute, it *must not* perform a `path.join()`, and instead do `fs.statSync(fileName);`. (NB, I don't know why, but I did a `code .` in the directory containing the .g4. But, it says the process current working directory is `"C:\Users\kenne\AppData\Local\Programs\Microsoft VS Code\"`. This makes zero sense.)
* If it throws an error, the extension should tell me what file it is trying to open. Instead, it [swallows the error, and sets source to ""](https://github.com/mike-lischke/vscode-antlr4/blob/95a2720d5dd9cc87203f59a650635e1657aa321f/src/backend/facade.ts#L94C19-L96C18). I have no idea why anything failed.

**Comment by mike-lischke** [comment] 2023-11-08 16:21
That might be a duplicate of #221. There's a problem with absolute paths, yes.

**Comment by kaby76** [comment] 2023-11-08 19:52
This change fixes at least the "absolute path" problem (ignore Log.debug() calls).
```
--- a/src/backend/facade.ts
+++ b/src/backend/facade.ts
@@ -7,6 +7,7 @@ import * as fs from "fs";
 import * as path from "path";

 import { Vocabulary } from "antlr4ng";
+import { Log } from "../frontend/Log.js";

 export interface IContextEntry {
     context: SourceContext;
@@ -85,13 +86,22 @@ export class AntlrFacade {
     }

     public loadGrammar(fileName: string, source?: string): SourceContext {
+Log.debug("LOADGRAMMAR " + fileName);
         let contextEntry = this.sourceContexts.get(fileName);
         if (!contextEntry) {
             if (!source) {
                 try {
-                    fs.statSync(path.join(process.cwd(), fileName));
+                       if (path.isAbsolute(fileName)) {
+                               fs.statSync(fileName);
+                       } else {
+                               fs.statSync(path.join(process.cwd(), fileName));
+                       }
                     source = fs.readFileSync(fileName, "utf8");
+Log.debug("fileName = '" + fileName + "'");
+Log.debug("source = '" + source + "'");
                 } catch (e) {
+Log.debug("CAUGHT LOADGRAMMAR empty");
+Log.debug("fileName = '" + fileName + "'");
                     source = "";
                 }
             }
```
But, it makes more sense to use the workspace folder rather than current working directory when joining paths.
```
	let folder = workspace.workspaceFolders ? workspace.workspaceFolders[0] : undefined;
	let folderPath = folder ? folder.uri.fsPath : undefined;
```
For all practical purposes, for a grammar file like "Test.g4", I cannot get input parameter `fileName` to be a relative path. It always appears to be an absolute path.

**Closed** 2023-11-26 15:48 UTC
