### ISSUE TITLE
Extension causes high cpu load, vscode extenstion host stops all together

### ISSUE THREAD

**Issue by Patco-Erold** [mike-lischke/vscode-antlr4#142] opened 2021-04-23 12:09 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-antlr4`
- Extension Version: `2.2.4`
- OS Version: `Linux x64 4.15.0-54-generic`
- VS Code version: `1.55.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/mike-lischke.vscode-antlr4-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mike-lischke** [comment] 2021-04-24 08:47
Is this a duplicate of #141 ?

**Comment by Patco-Erold** [comment] 2021-04-24 08:53
It seems like it, I will close this now, I was under pressure and stressed
I did not even read through the open/close *issues.*

Thank you.

**Closed** 2021-05-26 15:39 UTC
